# استفاده از ایمیج رسمی n8n
FROM n8nio/n8n

# ست کردن متغیرهای محیطی از Render (مقادیر رو در پنل Render تعریف کنید)
ENV N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
ENV N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
ENV N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
ENV N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
ENV GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
ENV WEBHOOK_URL=${WEBHOOK_URL}

# پورت پیش‌فرض n8n
EXPOSE 5678
